update workflows, decouple for ctf v1

diff --git a/.github/workflows/e2e_custom_cl.yml b/.github/workflows/e2e_custom_cl.yml
--- a/.github/workflows/e2e_custom_cl.yml
+++ b/.github/workflows/e2e_custom_cl.yml
@@ -12,6 +12,16 @@ on:
         description: Team to run the tests for (e.g. BIX, CCIP)
         required: true
         type: string
+  workflow_call:
+    inputs:
+      solana_ref:
+        required: false
+        type: string
+        description: "The chainlink-solana ref to checkout"
+    secrets:
+      CHAINLINK_IMAGE:
+        required: false
+        description: "Full ECR image URI with tag (e.g. <account>.dkr.ecr.<region>.amazonaws.com/<repo>:<tag>)"
 
 env:
   CL_ECR: ${{ secrets.QA_AWS_ACCOUNT_NUMBER }}.dkr.ecr.${{ secrets.QA_AWS_REGION }}.amazonaws.com/chainlink
@@ -30,6 +40,9 @@ jobs:
     steps:
       - name: Checkout sources
         uses: actions/checkout@v4
+        with:
+          repository: smartcontractkit/chainlink-solana
+          ref: ${{ inputs.solana_ref || '' }}
       - name: Setup go
         uses: actions/setup-go@v5
         with:
@@ -47,6 +60,9 @@ jobs:
     steps:
       - name: Checkout the repo
         uses: actions/checkout@v4
+        with:
+          repository: smartcontractkit/chainlink-solana
+          ref: ${{ inputs.solana_ref || '' }}
       - name: Get ProjectSerum Version
         id: psversion
         uses: ./.github/actions/projectserum_version
@@ -97,6 +113,9 @@ jobs:
     steps:
       - name: Checkout the repo
         uses: actions/checkout@v4
+        with:
+          repository: smartcontractkit/chainlink-solana
+          ref: ${{ inputs.solana_ref || '' }}
       - name: Build contracts
         uses: ./.github/actions/build_contract_artifacts
         with:
@@ -117,6 +136,7 @@ jobs:
       - name: Checkout previous release
         uses: actions/checkout@v4
         with:
+          repository: smartcontractkit/chainlink-solana
           ref: v1.0.2 # set to v1.1.0 after v1.1.0 is deployed to mainnet
       - name: build contracts
         id: previous
@@ -191,6 +211,7 @@ jobs:
 
   get-core-ref:
     name: Get Core Ref
+    if: ${{ !secrets.CHAINLINK_IMAGE }}
     runs-on: ubuntu-latest
     permissions:
       contents: read
@@ -201,6 +222,9 @@ jobs:
     steps:
       - name: Checkout the repo
         uses: actions/checkout@v4
+        with:
+          repository: smartcontractkit/chainlink-solana
+          ref: ${{ inputs.solana_ref || '' }}
 
       - name: Get core ref
         id: get-core-ref
@@ -208,6 +232,7 @@ jobs:
 
   e2e_custom_build_custom_chainlink_image:
     needs: [ get-core-ref ]
+    if: ${{ !secrets.CHAINLINK_IMAGE }}
     name: E2E Custom Build Custom CL Image
     runs-on: ubuntu-latest-16cores-64GB
     environment: integration
@@ -261,7 +286,8 @@ jobs:
       - name: Checkout the repo
         uses: actions/checkout@v4
         with:
-          ref: ${{ github.event.pull_request.head.sha }}
+          repository: smartcontractkit/chainlink-solana
+          ref: ${{ inputs.solana_ref || github.event.pull_request.head.sha }}
 
       - name: Build Image
         uses: ./.github/actions/build-test-image
@@ -271,7 +297,7 @@ jobs:
           QA_AWS_REGION: ${{ secrets.QA_AWS_REGION }}
           QA_AWS_ACCOUNT_NUMBER: ${{ secrets.QA_AWS_ACCOUNT_NUMBER }}
 
-  e2e_custom_run_smoke_tests:
+  e2e_custom_run_smoke_tests_matrix:
     name: E2E Smoke Tests (${{ matrix.variant }})
     environment: integration
     permissions:
@@ -288,10 +314,13 @@ jobs:
             configs: env.toml,products/solana/basic.toml,products/solana/plugins.toml
     needs: [e2e_custom_build_artifacts, e2e_custom_build_custom_chainlink_image, check_test_compilation]
     env:
-      CHAINLINK_IMAGE: ${{ secrets.QA_AWS_ACCOUNT_NUMBER }}.dkr.ecr.${{ secrets.QA_AWS_REGION }}.amazonaws.com/chainlink:solana.8ac5fcc771e6ede8e63b015a2a7e90315b24f274 #${{ github.sha }}
+      CHAINLINK_IMAGE: ${{ secrets.CHAINLINK_IMAGE || format('{0}.dkr.ecr.{1}.amazonaws.com/chainlink:solana.{2}', secrets.QA_AWS_ACCOUNT_NUMBER, secrets.QA_AWS_REGION, github.sha) }}
     steps:
       - name: Checkout the repo
         uses: actions/checkout@v4
+        with:
+          repository: smartcontractkit/chainlink-solana
+          ref: ${{ inputs.solana_ref || '' }}
 
       - name: Configure AWS Credentials
         uses: aws-actions/configure-aws-credentials@010d0da01d0b5a38af31e9c3470dbfdabdecca3a # v4.0.1
@@ -331,6 +360,10 @@ jobs:
           name: artifacts
           path: ${{ env.CONTRACT_ARTIFACTS_PATH }}
 
+      - name: Start fakes server
+        working-directory: integration-tests/devenv
+        run: go run ./fakes/cmd &
+
       - name: Setup Environment
         working-directory: integration-tests/devenv
         run: go run ./cmd u ${{ matrix.configs }}
@@ -353,6 +386,21 @@ jobs:
             integration-tests/smoke/logs/
           retention-days: 1
 
+  e2e_custom_run_smoke_tests:
+    name: E2E Custom Run Smoke Tests
+    runs-on: ubuntu-latest
+    needs: [e2e_custom_run_smoke_tests_matrix]
+    if: always()
+    steps:
+      - name: Check results
+        run: |
+          if [[ "${{ needs.e2e_custom_run_smoke_tests_matrix.result }}" == "success" ]]; then
+            echo "All smoke tests passed."
+          else
+            echo "Smoke tests failed: ${{ needs.e2e_custom_run_smoke_tests_matrix.result }}"
+            exit 1
+          fi
+
   e2e_program_upgrade_tests:
     name: E2E Program Upgrade Tests
     environment: integration
@@ -363,10 +411,13 @@ jobs:
     needs: [contract-changes,e2e_program_upgrade_generate_artifacts,e2e_custom_build_custom_chainlink_image, check_test_compilation]
     if: needs.contract-changes.outputs.changed == 'true' && needs.e2e_program_upgrade_generate_artifacts.outputs.changed == 'true'
     env:
-      CHAINLINK_IMAGE: ${{ secrets.QA_AWS_ACCOUNT_NUMBER }}.dkr.ecr.${{ secrets.QA_AWS_REGION }}.amazonaws.com/chainlink:solana.8ac5fcc771e6ede8e63b015a2a7e90315b24f274 #${{ github.sha }}
+      CHAINLINK_IMAGE: ${{ secrets.CHAINLINK_IMAGE || format('{0}.dkr.ecr.{1}.amazonaws.com/chainlink:solana.{2}', secrets.QA_AWS_ACCOUNT_NUMBER, secrets.QA_AWS_REGION, github.sha) }}
     steps:
       - name: Checkout the repo
         uses: actions/checkout@v4
+        with:
+          repository: smartcontractkit/chainlink-solana
+          ref: ${{ inputs.solana_ref || '' }}
 
       - name: Configure AWS Credentials
         uses: aws-actions/configure-aws-credentials@010d0da01d0b5a38af31e9c3470dbfdabdecca3a # v4.0.1
@@ -411,6 +462,10 @@ jobs:
         with:
           name: artifacts
           path: contracts/target/deploy-upgrade
+
+      - name: Start fakes server
+        working-directory: integration-tests/devenv
+        run: go run ./fakes/cmd &
 
       - name: Setup Environment
         working-directory: integration-tests/devenv
