update GH workflows, create reusable workflow

diff --git a/.github/workflows/e2e_custom_cl_reusable.yml b/.github/workflows/e2e_custom_cl_reusable.yml
--- a/.github/workflows/e2e_custom_cl_reusable.yml
+++ b/.github/workflows/e2e_custom_cl_reusable.yml
@@ -1,30 +1,23 @@
-name: e2e_testnet_daily
+name: e2e_tests_custom_cl_reusable
+
 on:
-  workflow_dispatch:
+  workflow_call:
     inputs:
-      cl_branch_ref:
-        description: Chainlink repo branch to integrate with
-        required: true
-        default: develop
-        type: string
-      test_secrets_override_key:
-        description: 'Key to run tests with custom test secrets like ws url, rpc url, private key, etc.'
-        required: false
-        type: string
-      team:
-        description: Team to run the tests for (e.g. BIX, CCIP)
+      solana_ref:
         required: true
         type: string
-  schedule:
-    - cron: '0 6 * * *'
-# Only run 1 of this workflow at a time per PR
+        description: "The chainlink-solana ref to checkout"
+    secrets:
+      chainlink_image:
+        required: true
+        description: "Full Chainlink image URI with tag"
+
 env:
   CONTRACT_ARTIFACTS_PATH: contracts/target/deploy
   MOD_CACHE_VERSION: 1
 
-# Only run 1 of this workflow at a time per PR
 concurrency:
-  group: integration-tests-solana-daily-${{ github.ref }}
+  group: integration-tests-solana-reusable-${{ inputs.solana_ref }}
   cancel-in-progress: true
 
 jobs:
@@ -34,6 +27,9 @@ jobs:
     steps:
       - name: Checkout sources
         uses: actions/checkout@v4
+        with:
+          repository: smartcontractkit/chainlink-solana
+          ref: ${{ inputs.solana_ref }}
       - name: Setup go
         uses: actions/setup-go@v5
         with:
@@ -51,6 +47,9 @@ jobs:
     steps:
       - name: Checkout the repo
         uses: actions/checkout@v4
+        with:
+          repository: smartcontractkit/chainlink-solana
+          ref: ${{ inputs.solana_ref }}
       - name: Get ProjectSerum Version
         id: psversion
         uses: ./.github/actions/projectserum_version
@@ -66,6 +65,9 @@ jobs:
     steps:
       - name: Checkout the repo
         uses: actions/checkout@v4
+        with:
+          repository: smartcontractkit/chainlink-solana
+          ref: ${{ inputs.solana_ref }}
       - name: Build contracts
         uses: ./.github/actions/build_contract_artifacts
         with:
@@ -73,37 +75,7 @@ jobs:
           image: backpackapp/build
           image-version: ${{ needs.get_projectserum_version.outputs.projectserum_version }}
 
-  e2e_custom_build_custom_chainlink_image:
-    name: E2E Custom Build Custom CL Image
-    runs-on: ubuntu-latest
-    environment: integration
-    permissions:
-      id-token: write
-      contents: read
-    env:
-      GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
-    steps:
-      - name: Check if image exists
-        id: check-image
-        uses: smartcontractkit/chainlink-github-actions/docker/image-exists@b49a9d04744b0237908831730f8553f26d73a94b # v2.3.17
-        with:
-          repository: chainlink
-          tag: solana.${{ github.sha }}
-          AWS_REGION: ${{ secrets.QA_AWS_REGION }}
-          AWS_ROLE_TO_ASSUME: ${{ secrets.QA_AWS_ROLE_TO_ASSUME }}
-      - name: Build Image
-        if: steps.check-image.outputs.exists == 'false'
-        uses: smartcontractkit/chainlink-github-actions/chainlink-testing-framework/build-image@b49a9d04744b0237908831730f8553f26d73a94b # v2.3.17
-        with:
-          should_checkout: true
-          cl_repo: smartcontractkit/chainlink
-          cl_ref: ${{ github.event.inputs.cl_branch_ref }}
-          dep_solana_sha: ${{ github.event.pull_request.head.sha }}
-          push_tag: ${{ env.CL_ECR }}:solana.${{ github.sha }}
-          QA_AWS_REGION: ${{ secrets.QA_AWS_REGION }}
-          QA_AWS_ROLE_TO_ASSUME: ${{ secrets.QA_AWS_ROLE_TO_ASSUME }}
-
-  e2e_custom_run_smoke_tests:
+  e2e_custom_run_smoke_tests_matrix:
     name: E2E Smoke Tests (${{ matrix.variant }})
     environment: integration
     permissions:
@@ -118,27 +90,15 @@ jobs:
             configs: env.toml,products/solana/basic.toml
           - variant: plugins
             configs: env.toml,products/solana/basic.toml,products/solana/plugins.toml
-    needs: [e2e_custom_build_artifacts, e2e_custom_build_custom_chainlink_image, check_test_compilation]
+    needs: [e2e_custom_build_artifacts, check_test_compilation]
     env:
-      CHAINLINK_IMAGE: ${{ format('{0}.dkr.ecr.{1}.amazonaws.com/chainlink:solana.{2}', secrets.QA_AWS_ACCOUNT_NUMBER, secrets.QA_AWS_REGION, github.sha) }}
+      CHAINLINK_IMAGE: ${{ secrets.chainlink_image }}
     steps:
       - name: Checkout the repo
         uses: actions/checkout@v4
-
-      - name: Configure AWS Credentials
-        uses: aws-actions/configure-aws-credentials@010d0da01d0b5a38af31e9c3470dbfdabdecca3a # v4.0.1
         with:
-          aws-region: ${{ secrets.QA_AWS_REGION }}
-          role-to-assume: ${{ secrets.QA_AWS_ROLE_TO_ASSUME }}
-          role-duration-seconds: 1800
-          mask-aws-account-id: true
-
-      - name: Authenticate to ECR
-        uses: aws-actions/amazon-ecr-login@062b18b96a7aff071d4dc91bc00c4c1a7945b076 # v2.0.1
-        with:
-          registries: ${{ secrets.QA_AWS_ACCOUNT_NUMBER }}
-        env:
-          AWS_REGION: ${{ secrets.QA_AWS_REGION }}
+          repository: smartcontractkit/chainlink-solana
+          ref: ${{ inputs.solana_ref }}
 
       - name: Install Solana CLI
         run: ./scripts/install-solana-ci.sh
@@ -188,3 +148,18 @@ jobs:
             integration-tests/devenv/logs/
             integration-tests/smoke/logs/
           retention-days: 1
+
+  e2e_custom_run_smoke_tests:
+    name: E2E Custom Run Smoke Tests
+    runs-on: ubuntu-latest
+    needs: [e2e_custom_run_smoke_tests_matrix]
+    if: always()
+    steps:
+      - name: Check results
+        run: |
+          if [[ "${{ needs.e2e_custom_run_smoke_tests_matrix.result }}" == "success" ]]; then
+            echo "All smoke tests passed."
+          else
+            echo "Smoke tests failed: ${{ needs.e2e_custom_run_smoke_tests_matrix.result }}"
+            exit 1
+          fi
