Adding go testS

diff --git a/.github/workflows/rust.yml b/.github/workflows/rust.yml
--- a/.github/workflows/rust.yml
+++ b/.github/workflows/rust.yml
@@ -39,84 +39,84 @@ jobs:
     runs-on: ubuntu-latest-8cores-32GB
     needs: [get_projectserum_version, build_wrapped_anchor_image]
     steps:
-    - uses: actions/checkout@v4
-    - name: Cache cargo target dir
-      uses: actions/cache@v4
-      with:
-        path: contracts/target
-        key: ${{ runner.os }}-v2-cargo-build-target-${{ hashFiles('contracts/**/Cargo.lock') }}
-    - name: Cache hello-world target dir
-      uses: actions/cache@v4
-      with:
-        path: contracts/examples/hello-world/target
-        key: ${{ runner.os }}-v2-cargo-build-target-hello-world-${{ hashFiles('contracts/**/Cargo.lock') }}
-    - name: cache docker build image
-      id: cache-image
-      uses: actions/cache@v4
-      with:
-        path: contracts/docker-build.tar
-        key: ${{ runner.os }}-docker-pnpm-build-${{ needs.get_projectserum_version.outputs.projectserum_version }}-${{ hashFiles('contracts/**/Cargo.lock') }}
-    - name: load cached image
-      run: |
-        docker load --input docker-build.tar
-    - name: run tests
-      run: |
-        docker run -v "$(pwd)/../":/repo chainlink-solana:build bash -c "\
-          set -eoux pipefail &&\
-          RUSTUP_HOME=\"/root/.rustup\" &&\
-          FORCE_COLOR=1 &&\
-          cd /repo/contracts &&\
-          solana-keygen new -o id.json --no-bip39-passphrase &&\
-          cd /repo/ts &&\
-          pnpm install --frozen-lockfile &&\
-          pnpm build &&\
-          cd /repo/contracts &&\
-          pnpm install --frozen-lockfile &&\
-          anchor test &&\
-          chmod -R 755 ./target &&\
-          cd /repo/contracts/examples/hello-world &&\
-          pnpm install --frozen-lockfile &&\
-          anchor test &&\
-          chmod -R 755 ./target"
+      - uses: actions/checkout@v4
+      - name: Cache cargo target dir
+        uses: actions/cache@v4
+        with:
+          path: contracts/target
+          key: ${{ runner.os }}-v2-cargo-build-target-${{ hashFiles('contracts/**/Cargo.lock') }}
+      - name: Cache hello-world target dir
+        uses: actions/cache@v4
+        with:
+          path: contracts/examples/hello-world/target
+          key: ${{ runner.os }}-v2-cargo-build-target-hello-world-${{ hashFiles('contracts/**/Cargo.lock') }}
+      - name: cache docker build image
+        id: cache-image
+        uses: actions/cache@v4
+        with:
+          path: contracts/docker-build.tar
+          key: ${{ runner.os }}-docker-pnpm-build-${{ needs.get_projectserum_version.outputs.projectserum_version }}-${{ hashFiles('contracts/**/Cargo.lock') }}
+      - name: load cached image
+        run: |
+          docker load --input docker-build.tar
+      - name: run tests
+        run: |
+          docker run -v "$(pwd)/../":/repo chainlink-solana:build bash -c "\
+            set -eoux pipefail &&\
+            RUSTUP_HOME=\"/root/.rustup\" &&\
+            FORCE_COLOR=1 &&\
+            cd /repo/contracts &&\
+            solana-keygen new -o id.json --no-bip39-passphrase &&\
+            cd /repo/ts &&\
+            pnpm install --frozen-lockfile &&\
+            pnpm build &&\
+            cd /repo/contracts &&\
+            pnpm install --frozen-lockfile &&\
+            anchor test &&\
+            chmod -R 755 ./target &&\
+            cd /repo/contracts/examples/hello-world &&\
+            pnpm install --frozen-lockfile &&\
+            anchor test &&\
+            chmod -R 755 ./target"
 
   rust_lint:
     name: Rust Lint
     runs-on: ubuntu-latest
     needs: [get_projectserum_version, build_wrapped_anchor_image]
     steps:
-    - uses: actions/checkout@v4
-    - name: Cache cargo target dir
-      uses: actions/cache@v4
-      with:
-        path: contracts/target
-        key: ${{ runner.os }}-v2-cargo-build-target-${{ hashFiles('contracts/**/Cargo.lock') }}
-    - name: cache docker build image
-      id: cache-image
-      uses: actions/cache@v4
-      with:
-        path: contracts/docker-build.tar
-        key: ${{ runner.os }}-docker-pnpm-build-${{ needs.get_projectserum_version.outputs.projectserum_version }}-${{ hashFiles('contracts/**/Cargo.lock') }}
-    - name: load cached image
-      run: |
-        docker load --input docker-build.tar
-    - name: format contracts + artifacts
-      run: |
-        npm install -g pnpm
-        pnpm install --frozen-lockfile
-        cd ../ # back to root
-        make format-contracts
-        echo "run 'make format-contracts' if this fails"
-        git diff --stat --exit-code
+      - uses: actions/checkout@v4
+      - name: Cache cargo target dir
+        uses: actions/cache@v4
+        with:
+          path: contracts/target
+          key: ${{ runner.os }}-v2-cargo-build-target-${{ hashFiles('contracts/**/Cargo.lock') }}
+      - name: cache docker build image
+        id: cache-image
+        uses: actions/cache@v4
+        with:
+          path: contracts/docker-build.tar
+          key: ${{ runner.os }}-docker-pnpm-build-${{ needs.get_projectserum_version.outputs.projectserum_version }}-${{ hashFiles('contracts/**/Cargo.lock') }}
+      - name: load cached image
+        run: |
+          docker load --input docker-build.tar
+      - name: format contracts + artifacts
+        run: |
+          npm install -g pnpm
+          pnpm install --frozen-lockfile
+          cd ../ # back to root
+          make format-contracts
+          echo "run 'make format-contracts' if this fails"
+          git diff --stat --exit-code
 
-    - name: cargo check
-      run: |
-        docker run -v "$(pwd)/../":/repo chainlink-solana:build bash -c "\
-          set -eoux pipefail &&\
-          RUSTUP_HOME=\"/root/.rustup\" &&\
-          FORCE_COLOR=1 &&\
-          cd /repo/contracts &&\
-          cargo check &&\
-          cargo clippy -- -D warnings"
+      - name: cargo check
+        run: |
+          docker run -v "$(pwd)/../":/repo chainlink-solana:build bash -c "\
+            set -eoux pipefail &&\
+            RUSTUP_HOME=\"/root/.rustup\" &&\
+            FORCE_COLOR=1 &&\
+            cd /repo/contracts &&\
+            cargo check &&\
+            cargo clippy -- -D warnings"
 
   relay_run_interface_tests:
     name: Relay Run Interface Tests
@@ -160,7 +160,7 @@ jobs:
       - name: Setup Postgres
         uses: smartcontractkit/.github/actions/setup-postgres@13b05e8b4e11a8c4402f8034daaf9a4332032dc7 # v1.0.0
         with:
-          tmpfs: 'true'
+          tmpfs: "true"
 
       - name: Get core ref
         id: get-core-ref
@@ -187,3 +187,48 @@ jobs:
 
           cd ..
           make test_relay_integration
+
+  go:
+    # needs: [ changes, get_anchor_version, build_solana ]
+    # if: ${{ needs.changes.outputs.solana_changes == 'true' }}
+    name: go tests
+    runs-on: ubuntu-latest-8cores-32GB
+    needs: [get_projectserum_version, build_wrapped_anchor_image]
+    steps:
+      - uses: actions/checkout@v4
+      - name: Cache cargo target dir
+        uses: actions/cache@1bd1e32a3bdc45362d1e726936510720a7c30a57 # v4.2.0
+        with:
+          path: contracts/target
+          key: ${{ runner.os }}-v2-cargo-build-target-${{ hashFiles('contracts/**/Cargo.lock') }}
+      - name: cache docker build image
+        id: cache-image
+        uses: actions/cache@1bd1e32a3bdc45362d1e726936510720a7c30a57 # v4.2.0
+        with:
+          path: contracts/docker-build.tar
+          key: ${{ runner.os }}-docker-pnpm-build-${{ needs.get_projectserum_version.outputs.projectserum_version }}-${{ hashFiles('contracts/**/Cargo.lock') }}
+      - name: load cached image
+        run: |
+          docker load --input contracts/docker-build.tar
+      - name: Setup go
+        uses: actions/setup-go@cdcb36043654635271a94b9a6d1392de5bb323a7 # v5.0.1
+        with:
+          go-version-file: "./go.mod"
+          check-latest: true
+          cache-dependency-path: "./go.sum"
+      - name: Install gotestloghelper
+        run: go install github.com/smartcontractkit/chainlink-testing-framework/tools/gotestloghelper@latest
+      # - name: Install Solana CLI
+      #   run: |
+      #     sh -c "$(curl -sSfL https://release.anza.xyz/stable/install)" # always use latest stable release from solana
+      #     echo "PATH=$HOME/.local/share/solana/install/active_release/bin:$PATH" >> $GITHUB_ENV
+      - name: build + test
+        run: |
+          set -eoux pipefail
+          # compile artifacts
+          docker run -v "$(pwd)/../":/repo chainlink-solana:build bash -c "\
+          set -eoux pipefail &&\
+          RUSTUP_HOME=\"/root/.rustup\" &&\
+          FORCE_COLOR=1 &&\
+          cd /repo/contracts/gotests &&\
+          go test -v ./...
